- hosts: localhost
  become: true
  environment:
    PATH: "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"

  tasks:
    - name: Do config tasks
      import_tasks:
        file: config_tasks.yaml

    - name: autofs directory
      when: nocommonmap is not defined or not nocommonmap
      file: path=/etc/auto.master.d mode=755 owner=root state=directory

    - name: home.autofs
      when: nocommonmap is not defined or not nocommonmap
      template: src="{{ playbook_dir }}/autofs-files/etc/auto.master.d/home.autofs" dest=/etc/auto.master.d/home.autofs mode=644 owner=root
      notify:
        - restart autofs

    - name: auto.home.panic
      when: nocommonmap is not defined or not nocommonmap
      template: src="{{ playbook_dir }}/autofs-files/etc/auto.master.d/{{ auto_home_file }}" dest=/etc/auto.master.d/auto.home mode=644 owner=root
      notify:
        - restart autofs

    - meta: flush_handlers

  handlers:
      - name: restart autofs
        service: name=autofs state=restarted enabled=yes
