- hosts: all
  become: true

  tasks:
    - name: Install CUDA
      when: cuda|default('false')|bool
      block:
        - name: Install new CUDA key
          apt:
            deb: "{{ cuda_repo_url }}/cuda-keyring_1.0-1_all.deb"
            state: present

        - name: Update APT cache
          apt:
            update_cache: yes

        - name: Install CUDA
          apt:
            name: cuda
            state: latest

        - name: Add symbolic link
          file:
            src: /usr/local/cuda-11
            dest: /usr/local/cuda
            state: link

        - name: Set system wide PATH
          blockinfile:
            path: /etc/profile.d/cuda-path.sh
            create: yes
            state: present
            block: |
              export PATH=$PATH:/usr/local/cuda/bin

        - name: Reboot the machine
          reboot:

  vars:
    cuda_repo_url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/
