- hosts: localhost
  become: true

  tasks:
    - name: Download CUDA PIN
      get_url:
        url: "{{ cuda_pin_url }}"
        dest: /etc/apt/preferences.d/cuda-repository-pin-600

    - name: Add CUDA APT key
      apt_key:
        url: "{{ cuda_key_url }}"

    - name: Add CUDA repo
      apt_repository:
        repo: "deb {{ cuda_repo_url }} /"
        state: present

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Install CUDA
      apt:
        name: cuda

  vars:
    cuda_pin_url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
    cuda_key_url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    cuda_repo_url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/
