- hosts: all
  become: true

  tasks:
    - name: Install Docker dependencies
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Add Docker GNUpg Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    # based on github.com/rbq/docker.yml
    # https://gist.github.com/rbq/886587980894e98b23d0eee2a1d84933
    - name: Add Docker repo for {{ ansible_distribution_release }}
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce

    - name: Install Docker Compose
      apt:
        name: docker-compose-plugin

    - name: Install daemon.json config file
      copy:
        src: config-files/docker-daemon.json
        dest: /etc/docker/daemon.json

    - name: Restart Docker daemon
      systemd:
        daemon_reload: true
        name: docker
        state: restarted
