- name: Remove existing Gurobi
  import_playbook: gurobi-remove.yaml

- hosts: all
  become: true

  vars_files: vars/gurobi.yaml

  tasks:
    - name: Fetch Gurobi archive
      get_url:
        url: "{{ GUROBI_TAR_URL }}"
        dest: /tmp
        checksum: "{{ GUROBI_TAR_CHECKSUM }}"
      register: download

    - name: Extract Gurobi archive
      unarchive:
        src: "{{ download.dest }}"
        dest: "{{ INSTALL_PATH }}"
        remote_src: yes

    - name: Set system wide PATH
      become: yes
      blockinfile:
        path: "{{ PROFILE_FILE }}"
        create: yes
        state: present
        block: |
          export PATH=$PATH:{{ GUROBI_INSTALL_DIR }}/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:{{ GUROBI_INSTALL_DIR }}/lib
          export GUROBI_HOME={{ GUROBI_INSTALL_DIR }}
