- name: Remove existing Gurobi
  import_playbook: gurobi-remove.yaml

- hosts: all
  become: true

  tasks:
    - name: Fetch Gurobi archive
      get_url:
        url: "{{ GUROBI_TAR_URL }}"
        dest: /tmp
        checksum: "{{ GUROBI_TAR_CHECKSUM }}"
      register: download

    - name: Extract Gurobi archive
      unarchive:
        src: "{{ download.dest }}"
        dest: "{{ INSTALL_PATH }}"
        remote_src: yes

    - name: Set system wide PATH
      become: yes
      blockinfile:
        path: "{{ PROFILE_FILE }}"
        create: yes
        state: present
        block: |
          export PATH=$PATH:{{ GUROBI_INSTALL_DIR }}/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:{{ GUROBI_INSTALL_DIR }}/lib
          export GUROBI_HOME={{ GUROBI_INSTALL_DIR }}

  vars:
    INSTALL_PATH: /opt
    GUROBI_TAR_URL: https://packages.gurobi.com/9.0/gurobi9.0.2_linux64.tar.gz
    GUROBI_TAR_CHECKSUM: "md5:cf8222318775f9ee58205bbb0ca0f1b5"
    GUROBI_VER: gurobi902
    GUROBI_INSTALL_DIR: "{{ INSTALL_PATH }}/{{ GUROBI_VER }}/linux64"
    PROFILE_FILE: /etc/profile.d/gurobi.sh
