- hosts: all
  become: true

  vars_files: vars/gurobi.yaml

  tasks:
    - name: Find existing Gurobi installs
      find:
        paths: "{{ INSTALL_PATH }}"
        patterns: "gurobi*"
        file_type: directory
      register: dirs_to_delete

    - name: Remove existing Gurobi installs
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ dirs_to_delete.files }}"

    - name: Remove existing profile script
      file:
        path: "{{ PROFILE_FILE }}"
        state: absent
