all:
  children:
    masters:
      hosts:
        parasol-master.cs.rutgers.edu:
        panic-master.cs.rutgers.edu:

    parasol:
      children:
        parasol_edge_xe3:
          hosts:
            parasol-edge-xe3-[00:07].cs.rutgers.edu:
          vars:
            qsv: true

        parasol_edge_xe3nv:
          hosts:
            parasol-edge-xe3nv-[00:03].cs.rutgers.edu:
          vars:
            cuda: true
            qsv: true

        parasol_edge_xd:
          hosts:
            parasol-edge-xd-[00:07].cs.rutgers.edu:

    panic:
      children:
        panic_cloud_xs:
          hosts:
            panic-cloud-xs-[00:07].cs.rutgers.edu:

        panic_cloud_gpu:
          hosts:
            panic-cloud-gpu-[00:02].cs.rutgers.edu:
          vars:
            cuda: true

        panic_cloud_optane:
          hosts:
            panic-cloud-optane-[00:01].cs.rutgers.edu:

        panic_desk:
          hosts:
            panic-desk-03.cs.rutgers.edu

    livestreaming:
      children:
        livestreaming_workers:
          hosts:
            parasol-edge-xe3-[00:07].cs.rutgers.edu:
            parasol-edge-xe3nv-[00:02].cs.rutgers.edu:
            parasol-edge-xd-[00:07].cs.rutgers.edu:

        livestreaming_scheduler:
          hosts:
            panic-cloud-xs-05.cs.rutgers.edu:

        livestreaming_big:
          children:
            livestreaming_big_cuda:
              hosts:
                panic-cloud-gpu-00.cs.rutgers.edu:
              vars:
                cuda: true
            livestreaming_big_nocuda:
              hosts:
                panic-cloud-00.cs.rutgers.edu:
                panic-cloud-05.cs.rutgers.edu:
                panic-cloud-optane-00.cs.rutgers.edu:
              vars:
                cuda: false
  vars:
    ansible_sudo_pass: "{{ ansible_ssh_pass }}"
    ansible_ssh_timeout: 60
    ansible_ssh_retries: 5
    ansible_remote_tmp: /tmp/.ansible-{{ ansible_user }}/tmp
    ansible_python_interpreter: /usr/bin/python3
