- hosts: all
  become: true

  tasks:
    - name: Enable GUC loading in /etc/default/grub
      replace:
        path: /etc/default/grub
        regexp: '(^GRUB_CMDLINE_LINUX_DEFAULT=)(.*)$'
        replace: '\1"i915.enable_guc=2"'
        backup: yes

    - name: Update GRUB
      command: update-grub
