- hosts: all
  become: true

  tasks:
    - name: Do config tasks
      import_tasks:
        file: config_tasks.yaml

    - name: add domain to hostname
      when: not '.' in hostname
      command: hostnamectl set-hostname {{ hostname }}.{{ domain }}

    - name: Reload facts in case the hostname changed
      setup:

    # we assume that it is good if it is already in place
    - name: Check for existing keytable
      stat:
        path: /etc/krb5.keytab
      register: keytab_stat

    - name: Set up a valid keytable
      block:
        - name: Get keytable
          command: curl --local-port 1-1023 -o /tmp/keytable https://{{ server }}/accounts/enrollhosts?host={{ hostname }}

        - name: Validate the keytable
          shell: "xxd /tmp/keytable | head -n 1 | grep 0502"
          register: keytab_validate
          ignore_errors: true

        - name: Fail if bad keytable
          fail:
            msg: "Bad or missing keytable"
          when: keytab_validate.rc != 0

        - name: Put keytable in place
          command: mv /tmp/keytable /etc/krb5.keytab

        - name: Set keytable permissions
          file:
            path: /etc/krb5.keytab
            state: touch
            mode: '0600'

      when: keytab_stat.stat.exists != true or (force_new_keytab is defined and force_new_keytab == '1')

    - name: Set up config file (login group {{ group }} / admin group {{ group_admin }}
      lineinfile:
        path: /etc/ansible/hosts
        state: present
        create: yes
        line: "localhost nfsserver=true local_homedir=true grouplist=coresysadmins,{{ group }} sudogroups=slide,{{ group_admin }} net_autofs=true domain=cs.rutgers.edu"
  vars:
    server: services.cs.rutgers.edu
    hostname: "{{ ansible_nodename }}"
    domain: cs.rutgers.edu
