- hosts: all
  become: true

  tasks:
    - name: Update Kerberos settings (Panic/Parasol)
      command: ansible-pull -f -U https://github.com/Rutgers-PANIC-Lab/Src-Infrastructure.git kerberos-init.yaml

    - name: Update Kerberos settings (LSCR)
      command: ansible-pull -f -U https://github.com/clhedrick/kerberos-ansible.git kerberos.yml

    - name: Reboot the machine
      reboot:
