- hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Install HWE kernel
      apt:
        name: linux-generic-hwe-18.04
        state: latest
        install_recommends: yes

    - name: Remove dependencies that are no longer required (with purge)
      apt:
        autoremove: yes
        purge: yes

    - name: Reboot the machine
      reboot:

