- hosts: all
  become: true

  tasks:
    - name: stop kubelet service
      systemd:
        name: kubelet
        state: stopped
      ignore_errors: yes

    - name: stop httpserver service
      systemd:
        name: httpserver
        state: stopped
      ignore_errors: yes
