- hosts: all
  become: true

  tasks:
    - name: Update kube apt key
      command: "bash -c 'curl -f https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -'"

    - name: Unhold kube packages
      command: apt-mark unhold kubeadm kubectl kubelet kubernetes-cni kube*

    - name: Remove kube packages
      apt:
        pkg:
          - kubeadm
          - kubectl
          - kubelet
          - kubernetes-cni
          - kube*
        state: absent
        purge: yes

    - name: Remove dependencies that are no longer required (with purge)
      apt:
        autoremove: yes
        purge: yes
