- hosts: all
  become: true

  tasks:
    - name: Find livestreaming logs
      find:
        paths: /var/log/livestreaming
        patterns: "*.log"
        file_type: file
      register: log_files

    - name: Fetch all livestreaming logs
      fetch:
        src: "{{ item.path }}"
        dest: "{{ DEST_DIR }}"
        flat: yes
      with_items: "{{ log_files.files }}"

  vars:
    DEST_DIR: /home/wkatsak/Src-Livestreaming/logs/
