- name: Remove existing install
  import_playbook: livestreaming-remove.yaml

- hosts: all
  become: true

  vars_files: vars/livestreaming.yaml

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python3-pip
          - virtualenv

    - name: Copy key file
      copy:
        src: /home/wkatsak/Src-Livestreaming/ssh/id_rsa
        dest: /tmp/id_rsa
        mode: '0600'

    - name: Clone repo
      git:
        repo: git@github.com:Rutgers-PANIC-Lab/Src-Livestreaming.git
        dest: "{{ LIVESTREAMING_INSTALL_DIR }}"
        accept_hostkey: yes
        key_file: /tmp/id_rsa

    - name: Delete key file
      file:
        name: /tmp/id_rsa
        state: absent

    - name: Create virtualenv
      command: virtualenv -p python3 {{ LIVESTREAMING_VENV_DIR }}

    - name: Install requirements
      command: "{{ LIVESTREAMING_PYTHON_BIN }} -m pip install -r {{ LIVESTREAMING_INSTALL_DIR }}/requirements.txt"

    - name: Install py-rapl
      command: "{{ LIVESTREAMING_PYTHON_BIN }} -m pip install git+https://github.com/wkatsak/py-rapl"

    - name: Install service unit files
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/{{ item }}"
        dest: "/etc/systemd/system/livestreaming-{{ item }}"
        remote_src: yes
      with_items:
        - node.service
        - streamgen.service

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Install default environment file
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/configs/livestreaming-default"
        dest: "{{ LIVESTREAMING_ENVIRONMENT_FILE}}"
        remote_src: yes

    - name: "Install qsv environment file"
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/configs/livestreaming-qsv"
        dest: "{{ LIVESTREAMING_ENVIRONMENT_FILE }}"
        remote_src: yes
      when: "'parasol_edge_xe3' in group_names"

    - name: "Install qsv/nv environment file"
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/configs/livestreaming-qsv-nv"
        dest: "{{ LIVESTREAMING_ENVIRONMENT_FILE}}"
        remote_src: yes
      when: "'parasol_edge_xe3nv' in group_names"

    - name: Create log directory
      file:
        path: "{{ LIVESTREAMING_LOG_DIR }}"
        state: directory
        mode: ugo+rw
