- name: Remove existing install
  import_playbook: livestreaming-remove.yaml

- hosts: all
  become: true

  vars_files:
    - vars/livestreaming.yaml
    - vars/python.yaml

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - python3-pip
          - virtualenv

    - name: Copy key file
      copy:
        src: "{{ LIVESTREAMING_LOCAL_PATH }}/ssh/id_rsa"
        dest: /tmp/id_rsa
        mode: '0600'

    - name: Clone repo
      git:
        repo: git@github.com:Rutgers-PANIC-Lab/Src-Livestreaming.git
        dest: "{{ LIVESTREAMING_INSTALL_DIR }}"
        accept_hostkey: yes
        key_file: /tmp/id_rsa

    - name: Delete key file
      file:
        name: /tmp/id_rsa
        state: absent

    - name: Create virtualenv
      command: virtualenv -p {{ PYTHON_BIN }} {{ LIVESTREAMING_VENV_DIR }}
      environment:
        LD_LIBRARY_PATH: "{{ PYTHON_INSTALL_DIR }}/lib"

    - name: Install requirements
      command: "{{ LIVESTREAMING_PYTHON_BIN }} -m pip install -r {{ LIVESTREAMING_INSTALL_DIR }}/requirements.txt"
      environment:
        LD_LIBRARY_PATH: "{{ PYTHON_INSTALL_DIR }}/lib"

    - name: Install py-rapl
      command: "{{ LIVESTREAMING_PYTHON_BIN }} -m pip install git+https://github.com/wkatsak/py-rapl"
      environment:
        LD_LIBRARY_PATH: "{{ PYTHON_INSTALL_DIR }}/lib"

    - name: Install matlab_model_utilties package
      command: "{{ LIVESTREAMING_PYTHON_BIN }} setup.py install"
      args:
        chdir: "{{ LIVESTREAMING_INSTALL_DIR }}/matlab_scripts/python_binding"
      environment:
        LD_LIBRARY_PATH: "{{ PYTHON_INSTALL_DIR }}/lib"

    - name: Install service unit files
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/{{ item }}"
        dest: "/etc/systemd/system/livestreaming-{{ item }}"
        remote_src: yes
      with_items:
        - node.service
        - streamgen.service

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Install default environment file
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/configs/worker-default"
        dest: "{{ LIVESTREAMING_ENVIRONMENT_FILE}}"
        remote_src: yes

    - name: "Install xe3 environment file"
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/configs/worker-xe3"
        dest: "{{ LIVESTREAMING_ENVIRONMENT_FILE }}"
        remote_src: yes
      when: "'parasol_edge_xe3' in group_names"

    - name: "Install xe3nv environment file"
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/configs/worker-xe3nv"
        dest: "{{ LIVESTREAMING_ENVIRONMENT_FILE}}"
        remote_src: yes
      when: "'parasol_edge_xe3nv' in group_names"

    - name: "Install xd environment file"
      copy:
        src: "{{ LIVESTREAMING_INSTALL_DIR }}/systemd/configs/worker-xd"
        dest: "{{ LIVESTREAMING_ENVIRONMENT_FILE}}"
        remote_src: yes
      when: "'parasol_edge_xd' in group_names"

    - name: Create log directory
      file:
        path: "{{ LIVESTREAMING_LOG_DIR }}"
        state: directory
        mode: ugo+rw
