- hosts: all
  become: true

  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - unzip
          - libxt6

    - name: Remove any existing MATLAB Runtime installs
      file:
        path: "{{ matlab_install_path_prefix }}"
        state: absent

    - name: Download MATLAB Runtime
      get_url:
        url: "{{ matlab_runtime_url }}"
        dest: /tmp
      register: get_url_result

    - name: Create MATLAB installer directory
      file:
        path: "{{ matlab_installer_path }}"
        state: directory

    - name: Extract MATLAB Runtime
      unarchive:
        src: "{{ get_url_result.dest }}"
        dest: "{{ matlab_installer_path }}"
        remote_src: yes

    - name: Install MATLAB Runtime
      command: ./install -mode silent -agreeToLicense yes -destinationFolder {{ matlab_install_path }}
      args:
        chdir: "{{ matlab_installer_path }}"

    - name: Set LD_LIBRARY_PATH
      blockinfile:
        path: /etc/profile.d/matlab-runtime.sh
        create: yes
        state: present
        block: |
          export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:{{ matlab_full_path }}/runtime/glnxa64:{{ matlab_full_path }}/bin/glnxa64:{{ matlab_full_path }}/sys/os/glnxa64:{{ matlab_full_path }}/sys/opengl/lib/glnxa64
        backup: yes

    - name: Remove MATLAB installer directory
      file:
        path: "{{ matlab_installer_path }}"
        state: absent

    #- name: Find MATLAB libexpat files
    #  find:
    #    paths: "{{ matlab_full_path }}"/bin/glnxa64"
    #    patterns: libexpat.*
    #  register: files_to_delete

    #- name: Delete MATLAB libexpat files
    #  file:
    #    path: "{{ item.path }}"
    #    state: absent
    #  with_items: {{ files_to_delete.files }}

  vars:
    matlab_runtime_version: R2021b
    matlab_runtime_version_code: v911
    matlab_runtime_url: https://ssd.mathworks.com/supportfiles/downloads/R2021b/Release/0/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2021b_glnxa64.zip
    matlab_installer_path: /tmp/matlab_runtime_installer
    matlab_install_path_prefix: /usr/local/MATLAB/Runtime
    matlab_install_path: "{{matlab_install_path_prefix}}/{{ matlab_runtime_version }}"
    matlab_full_path: "{{ matlab_install_path }}/{{ matlab_runtime_version_code }}"
