- hosts: all
  become: true

  tasks:
  # install node-exporter
  - name: Install node-exporter
    shell: |
            sudo apt-get update && sudo apt-get install -y prometheus-node-exporter

  # Update config file
  - name: Update Node Exporter config file
    lineinfile:
      path: /etc/default/prometheus-node-exporter
      regexp: '^ARGS='
      line: 'ARGS="--collector.disable-defaults --collector.cpu --collector.cpufreq --collector.diskstats --collector.nvme --collector.meminfo --collector.rapl --collector.thermal_zone --collector.netstat --collector.loadavg --collector.filesystem"'
  
  # Enable and start service
  - name: Enable prometheus-node-exporter service
    systemd:
      name: prometheus-node-exporter
      enabled: yes
      masked: no

  - name: Start prometheus-node-exporter service
    systemd:
      name: prometheus-node-exporter
      state: started