- hosts: all
  become: true

  tasks:
    - name: Update Hostname
      hostname:
        name: "{{ server_fqdn }}"
        use: systemd

    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        search_string: "127.0.1.1"
        line: "127.0.1.1 {{ server_hostname }}"

    - name: Reboot machine
      reboot:
        msg: Rebooting now!

  vars:
    server_type: "{{ inventory_hostname.split('-')[:3] | join('-') }}"
    server_hostname: "{{ inventory_hostname.replace('.cs.rutgers.edu', '') }}"
    server_fqdn: "{{ inventory_hostname }}"
