- hosts: all
  become: true

  tasks:
    - name: Check for /dev/sda
      stat:
        path: /dev/sda
      register: stat_sda_result

    - name: Get smartctl test result on /dev/sda
      command:
        cmd: "bash -c 'smartctl -a /dev/sda | grep Extended'"
      when: stat_sda_result.stat.exists and stat_sda_result.stat.isblk

    - name: Get smartctl test result on /dev/sda
      command:
        cmd: "bash -c 'smartctl -a /dev/sda | grep Raw_Read_Error_Rate'"
      when: stat_sda_result.stat.exists and stat_sda_result.stat.isblk

    - name: Get model number on /dev/sda
      command:
        cmd: "bash -c 'smartctl -a /dev/sda | grep \"Device Model\"'"
      when: stat_sda_result.stat.exists and stat_sda_result.stat.isblk

    - name: Get serial number on /dev/sda
      command:
        cmd: "bash -c 'smartctl -a /dev/sda | grep \"Serial Number\"'"
      when: stat_sda_result.stat.exists and stat_sda_result.stat.isblk

    - name: Get serial number on /dev/sda
      command:
        cmd: "bash -c 'smartctl -a /dev/sda | grep \"Firmware\"'"
      when: stat_sda_result.stat.exists and stat_sda_result.stat.isblk
